### PR TITLE
Use the 3ds-cmake for better compatibility

### PR DESCRIPTION
**Pull request by Lectem**
This helps to clean the CMakeLists.txt a bit, and fix the build for those under Windows.
This is based on https://github.com/Lectem/3ds-cmake

### CODE REVIEW

**Comment by endrift** [comment]
Been thinking about this, and I think it'd be quite a bit overkill, and widely asymmetrical with the other platforms which have similar problems to solve but don't go above and beyond like this. It's a nice framework, but I don't think mGBA has much use for the cruft that comes along with it above what's already done (and was just done recently).

Sorry.

**Comment by Lectem** [comment]
No problem, but would it be possible to at least fix the toolchain file for windows users?

**Comment by endrift** [comment]
I did that last night:

**Comment by Lectem** [comment]
Oh right, didn't see it

**Pull request closed without merging**
