### PR TITLE
HiDPI support for Qt GUI

### PR DESCRIPTION
**Pull request by KAMiKAZOW**
Fix blurry icons on buttons with High DPI screens.

Before:

Screenshot_20190608_202954

After:

Screenshot_20190608_205530

### CODE REVIEW

**Comment by endrift** [comment]
Should this be behind a conditional, testing for if the display is HiDPI?

**Comment by KAMiKAZOW** [comment]
> Should this be behind a conditional, testing for if the display is HiDPI?

Not according to a KDE developer who told me that in the context of another application. I'll happily test a build with that line on my crappy old notebook.

**Comment by endrift** [comment]
Seems like a worthwhile test. Let me know how it goes and I'll merge the patch.

**Comment by KAMiKAZOW** [comment]
I'll try to remember to do that the day after tomorrow.

**Comment by KAMiKAZOW** [comment]
Absolutely no problem on my crap low DPI notebook:

Screenshot_20190615_203241b

**Pull request merged**
