### PR TITLE
Video: Fix YUV420p being selected for video encoders that don't support it

### LINKED ISSUE #2084: Recording always forces yuv420p for h264 codecs even if encoder doesn't support it
Hi, I built `mgba-qt` from source on Ubuntu Focal. I tried to record with the 'lossless' preset and got an error.
```
[libx264rgb @ 0x55d9e8876300] Specified pixel format yuv420p is invalid or not supported
```
found this bug
```
if (encoder->video->codec->id == AV_CODEC_ID_H264 &&
    (strcasecmp(encoder->containerFormat, "mp4") ||
        strcasecmp(encoder->containerFormat, "m4v") ||
        strcasecmp(encoder->containerFormat, "mov"))) {
    // QuickTime and a few other things require YUV420
    encoder->video->pix_fmt = AV_PIX_FMT_YUV420P;
}
```
`strcasecmp` returns zero when strings are equal, this code to assumes the opposite.

### PR DESCRIPTION
**Pull request by luctowers**
Fixes #2084

### CODE REVIEW

**Comment by endrift** [comment]
This PR is incomplete--for one, that erroneous check is still in other places in the same file. Further, you should also check the actual encoder, not just the codec.

**Comment by luctowers** [comment]
Alright, if it's ok, I'm going give amending this PR a shot. If it doesn't pan out you can create one yourself :)

**Comment by luctowers** [comment]
hold on, I screwed up the enum comparison. :(

**Comment by luctowers** [comment]
last check didn't go through because of docker rate limiting

**Pull request closed without merging**
