### PR TITLE
fix build issues on ubuntu

### PR DESCRIPTION
**Pull request by ikeboy**
This fixes https://github.com/mgba-emu/mgba/issues/18 for me.

### CODE REVIEW

**Comment by endrift** [comment]
This fix is not correct. Q_OBJECT is necessary for any object that has slots, as this does.

**Comment by ikeboy** [comment]
I'm not sure what exactly the problem is, but removing that line lets it build and run fine, while there are errors with it.

**Comment by endrift** [comment]
That's a coincidence. The real problem appears to be that the file is being built without `BUILD_SDL` being defined. I'm assuming that with this being built as it is, the SDL option does not show up in Settings > Audio driver?

**Comment by ikeboy** [comment]
>SDL option does not show up in Settings > Audio driver?

It does, actually.

**Pull request closed without merging**
