### PR TITLE
Qt: Update German GUI translation

### PR DESCRIPTION
**Pull request by rootfather**
Synced with the changes made to the mGBA branch.
Also added a few DS specific strings. Except of the
IOViewer, the translation is now complete.

### CODE REVIEW

**Comment by endrift** [comment]
Please rebase

**Comment by rootfather** [comment]
Sorry m, I don't get what I should rebase since it is only one commit? I synced it by manually copying the mGBA.ts file and rebuilding the translations on the medusa branch, so technically the commit should be clean.

**Comment by endrift** [comment]
screen shot 2017-04-27 at 1 35 10 am

Turns out when I merged master back into medusa it broke your "clean" commit.

**Comment by rootfather** [comment]
Erm, that's weird. I'll see what I can do about this issue later today.

**Comment by endrift** [comment]
It's...not weird at all. The file changed on master. You copied the version from master onto a different branch, then made additional changes. Then the version on master got merged into that other branch. Your changes are stuck in between.

**Comment by rootfather** [comment]
Problems solved.

**Pull request merged**
