### PR TITLE
Some small fixes.

### PR DESCRIPTION
**Pull request by EmpyreusX**
Mentioned in #1845.

### CODE REVIEW

**Comment by endrift** [comment]
I'm ok merging this if @leoxxx thinks this is more appropriate than 窗口大小, otherwise you might want to discuss the difference.

**Comment by EmpyreusX** [comment]
> I'm ok merging this if @leoxxx thinks this is more appropriate than 窗口大小, otherwise you might want to discuss the difference.

We both agreed the translation.

**Comment by endrift** [comment]
I'm going to wait until I wake up (it's late here) to merge this in case you have any final things you want to touch up while I'm sleeping.

**Comment by EmpyreusX** [comment]
> I'm going to wait until I wake up (it's late here) to merge this in case you have any final things you want to touch up while I'm sleeping.

It's all done. You can merge these commits.

**Pull request merged**
