### PR TITLE
Create mgba-it.ts

### PR DESCRIPTION
**Pull request by theheroGAC**
Italian translation rev.1

### CODE REVIEW

**Comment by endrift** [comment]
Please mention that you've added an Italian language translation in the CHANGES file. See also how it's done for Spanish and German in the file already.

**Comment by theheroGAC** [comment]
update the CHANGES file with "Qt: Italian translation rev1.1 (by theheroGAC)" ?

**Comment by endrift** [comment]
Please don't version it. There's no reason to have a separate number from mGBA's version.

**Comment by theheroGAC** [comment]
ok and sorry :( Update CHANGES file thank you

**Pull request merged**
