### PR TITLE
disable full screen double-click

### PR DESCRIPTION
**Pull request by anthonydo8196**
Changes for this issue:  #2632 

Disabled full screen double-click

### CODE REVIEW

**Comment by endrift** [comment]
All I see is a setting and plumbing for it. I don't see where it actually _does_ the disabling. Furthermore, I don't want a setting. The feature should just be removed entirely, as it won't work with medusa (which is still on a branch).

**Comment by anthonydo8196** [comment]
Sorry, I did forget to add the functionality code. I have pushed it in a second commit.

**Comment by anthonydo8196** [comment]
I will get to removing the code after finals sorry.

**Comment by endrift** [comment]
Are you planning to finish this PR now that the semester is (presumably) over?

**Comment by Testsr** [comment]
@anthonydo8196 Are you going to be working on it?

**Comment by endrift** [comment]
It's been 3 weeks now, I'm just closing this.

**Pull request closed without merging**
