### PR TITLE
Qt: Add German GUI translation

### PR DESCRIPTION
**Pull request by rootfather**
This is my German translation of the mGBA Qt GUI. It is pretty much complete, there are only a few strings in the IOViewer missing that I am currently unable to translate due to a lack of understanding how those things work. I will try to figure this out as soon as possible.

There are currently 17 untranslated strings and 11 unfinished (aka questionable) strings left. I merged in the missing strings KDDLB found yesterday.

Feedback is greatly appreciated.

### CODE REVIEW

**Comment by rootfather** [comment]
Except for some strings in the IOViewer, the translation is now complete.

**Comment by endrift** [comment]
Please rebase over current changes, and squash the improved version into the old version.

**Comment by rootfather** [comment]
I rebased the current changes and sqzashed the improved version into the old one, as you requested.

**Comment by rootfather** [comment]
I just updated this PR again to include the changes made in af96097bb1cb1a0d2683f831370caa40a96541db.

**Comment by rootfather** [comment]
@endrift, could you please merge this PR at the current stage? It seems that I need more time to figure out all the IOViewer strings, so maybe we shouldn't wait any longer for the rest of the translation...

**Comment by endrift** [comment]
Alright. Those strings are less important anyway.

**Pull request merged**
