### PR TITLE
New shaders

### PR DESCRIPTION
**Pull request by Iniquitatis**
Added simplest possible configurable shaders.

(I think it will be more useful in this repository than just on my HDD. :))

### CODE REVIEW

**Comment by endrift** [comment]
Please use e.g. -2 for dimensions to be 2x input. The syntax needs some refreshing, but this avoids the problem of having the shaders be broken for GB. I see I forgot to do this in my shaders though.

**Comment by Iniquitatis** [comment]
Thanks for review.

**Comment by Iniquitatis** [comment]
(Closed again by accident, sorry. I'm writing from mobile browser.)

**Comment by endrift** [comment]
For height/width. Integer scaling just constrains the dimensions of the frame buffer to any integer multiple instead of a specific size, IIRC. You may need to experiment a bit.

**Comment by Iniquitatis** [comment]
Done and tested. Do I need to fix anything else?

**Comment by endrift** [comment]
I'll take a closer look when I get a chance but you're probably fine. Won't be able to merge for a few hours though.

**Comment by Iniquitatis** [comment]
Fixed capital letters in several names and squashed all existing commits.

**Comment by Iniquitatis** [comment]
Fixed scanlines scaling and squashed last commits again. Sorry for inconvenience.

**Comment by endrift** [comment]
Sorry for the delay; I've been really busy the past few days. I'll try to get to this tonight or tomorrow. I don't expect there to be any further hiccups that would require revisions on your end though.

**Comment by Iniquitatis** [comment]
Ah, it's okay. I'm away from my PC (actually, from stable internet connection) for another week, so it's highly unlikely I can fix anything here for now.

**Pull request merged**
