### PR TITLE
GBA: Fix MSR when execution mode changes to Thumb

### PR DESCRIPTION
**Pull request by MerryMage**
Testcases available.

### CODE REVIEW

**Comment by endrift** [comment]
I'm confused by the presence of the nop. How does that affect timing?

**Comment by MerryMage** [comment]
Here are a couple of testcases: https://gist.github.com/MerryMage/529d888834963d9128bab6156fe33b97

When CPSR.T is set while you're in ARM state, the following happens: (Take $ to be the address of the MSR instruction)

1. The instruction currently being decoded ($+4) is discarded. This wastes a cycle.
2. The low-word of the instruction already fetched ($+8) is interpreted as normal.
3. Execution continues as normal from ($+12).

Note that this means that any thumb instructions that may reside at ($+4), ($+6), ($+10) do not get executed.

**Comment by endrift** [comment]
Is there a source on that info? I can look into it a bit but merging this isn't dependent on that.

**Comment by endrift** [comment]
Can you add an entry to the changelog?

**Comment by MerryMage** [comment]
Added.

**Pull request merged**
